Saaya on swipe
globaltimer/Android-App pull request #17
Opened 2017-02-10 01:54 UTC by Saayaman

Hondyの書いたswipeをそのまま入れて見たけど、一つだけ

line 42の
//        binding = DataBindingUtil.setContentView(this, R.layout.activity_list);

が文句を言ってて原因がわからず・・・・。

2017-02-10 03:12 UTC, HoNKoT commented
どのそーす？
AndroidStudioでその行選択して、右クリックからOpenOnGitHubを選ぶと
[いい感じ](https://github.com/globaltimer/Android-App/blob/2e59bc6eb3fa9196f8f00abbd24a9e8705ad1683/app/src/main/java/honkot/gscheduler/AddCompareLocaleActivity.java#L139-L139)にハイライトかかったリンク作ってくれるから、それはっつけてくれると助かる
![screen shot 2017-02-09 at 7 09 35 pm](https://cloud.githubusercontent.com/assets/2055607/22812739/5b81229c-eefb-11e6-8a7c-ec62a7aa1886.png)

2017-02-28 21:13 UTC, HoNKoT requested changes
コメントの確認をお願い。
あと潜在バグが怖いので修正も必須だけど、これおれがした方がいい？

2017-02-28 21:13 UTC, HoNKoT commented on app/src/main/java/honkot/gscheduler/ListActivity.java
> +    private GoogleApiClient client;
これ何に使ってるの？？

2017-02-28 21:13 UTC, HoNKoT commented on app/src/main/java/honkot/gscheduler/ListActivity.java
> +                .setUrl(Uri.parse("http://[ENTER-YOUR-URL-HERE]"))
見た感じ、自分のサーバなのかFirebaseのURLなのかを指定しないと機能しない気が。。。
これそもそも機能してる？？

2017-02-28 21:13 UTC, HoNKoT commented on app/src/main/java/honkot/gscheduler/MyRecAdapter.java
> +            super(binding.rowRoot);
これは特に理由ないなら戻してほしい。
getRootはinflateしたViewを返す、rowRootはそのViewの中でもidがrowRootになってるViewを返してる。
返すべきはinflateしたViewそのままであるべきなのでgetRootが正解

2017-02-28 21:13 UTC, HoNKoT commented on app/src/main/java/honkot/gscheduler/MyRecAdapter.java
> +    CompareLocale item;
このitemをGlobalにするのはやめよう。
いろんなメソッドが不確定な順で呼ばれる状況の中で、ひとつのitemを更新したりremoveしたりするのは、予想外の事態が起きる危険があるのでやめたほうがいい。

2017-02-28 21:40 UTC, Saayaman commented on app/src/main/java/honkot/gscheduler/ListActivity.java
> +    private GoogleApiClient client;
削除対象

2017-02-28 21:52 UTC, Saayaman commented
@HoNKoT 直した！

2017-02-28 23:15 UTC, HoNKoT commented
これで動くならオッケー

2017-02-28 23:15 UTC, HoNKoT approved these changes

2017-02-28 23:45 UTC, merged