listView追加
globaltimer/Android-App pull request #2
Opened 2017-01-26 03:55 UTC by Saayaman

List View追加したよん。
チェックお願いします。

2017-01-30 23:49 UTC, HoNKoT commented
reviewしてコミットしますん

2017-01-31 00:16 UTC, HoNKoT requested changes
text1, 2, 3の箇所は必須で修正しといてくださいー。
ロジックは多分問題なし。

2017-01-31 00:16 UTC, HoNKoT commented on app/src/main/java/honkot/gscheduler/ListActivity.java
> +            TextView timeTextView = (TextView)view.findViewById(R.id.text3);
授業中とかテストプロジェクトはtext1とかでも問題ないけど、
可読性（読みやすさ）の面で本プロジェクトでは問題視される。

何を取得してるのか？がわかるように、
id も cityTextView とかにしたほうがいい。

（このtext1をクリックしてShift+F6か、右クリック Refactor>Renameで簡単に一括で変更可能）

2017-01-31 00:16 UTC, HoNKoT commented on app/src/main/java/honkot/gscheduler/utils/AdapterGenerater.java
> +//import honkot.gscheduler.adapter.LocaleAdapter;
こういうのは消した方がいい

実は自動で消す機能もIDEについてたりする。
http://stackoverflow.com/questions/22273434/remove-unused-imports-in-android-studio

"Settings->Editor->Auto Import->Optimize Imports on the fly"

2017-01-31 00:16 UTC, HoNKoT commented on app/src/main/java/honkot/gscheduler/ListActivity.java
> +//        worldTimes.add(new Times("Berlin", "08:00", "AM", "Dec 20th 2017", false));
不要なら消した方がいい。
あるいは「後々消す」ということでTODOコメントつけとくと、忘れるの防止できるのでしたほうがいいと思う。

2017-01-31 00:17 UTC, HoNKoT commented on .idea/encodings.xml
> -</project>
てst

2017-01-31 00:50 UTC, Saayaman commented on app/src/main/java/honkot/gscheduler/ListActivity.java
> +            TextView timeTextView = (TextView)view.findViewById(R.id.text3);
RenameOK!

2017-01-31 00:52 UTC, merged

2017-01-31 01:00 UTC, HoNKoT commented on app/src/main/java/honkot/gscheduler/ListActivity.java
> +            TextView timeTextView = (TextView)view.findViewById(R.id.text3);
修正なしでマージされとるw